"use client"

import type { Metadata } from "next";
import Link from "next/link";
import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type NavItem = {
  name: string;
  href: string;
};

const navLinks: NavItem[] = [
  {name: 'Login',href: '/login',},
  {name: 'Register',href: '/register',},
  {name: 'forget-passowrd',href: '/forget-passowrd',},
];

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname()
  return (
    <html lang="en">
      <body
      >
        <header>
          {
            navLinks.map((a,i)=>{
              const isActive = pathName == a.href || (pathName.startsWith(a.href) && pathName != '/')
              return(
                <Link href={a.href} key={i} className={isActive ?'textblue-400':'text-red-600'}>{a.name}</Link>
              )
            })
          }
        </header>
        <h1>this is auth layout</h1>
        {children}
      </body>
    </html>
  );
}
