import type { Metadata } from "next";
import NavBar from "./_component/Navbar";
import Footer from "./_component/Footer";
import { EtherProvider } from "./_component/EtherContext";

export const metadata: Metadata = {
  title: "This is ethers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <EtherProvider>
      <section >
        <NavBar />
        <h1>this is ether layout</h1>
        {children}
        <Footer />
      </section>
    </EtherProvider>
  );
}
